version: "3.9"

services:

  # ---------------------------------
  # DATABASE
  # ---------------------------------

  dwh_db:
    image: postgres:15
    container_name: dwh_db
    environment:
      POSTGRES_USER: ${DWH_DB_USER}
      POSTGRES_PASSWORD: ${DWH_DB_PASSWORD}
      POSTGRES_DB: ${DWH_DB_NAME}
    ports:
      - "5432:${DWH_DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # ---------------------------------
  # CHROME SERVICE
  # ---------------------------------

  chrome:
    image: selenium/standalone-chrome:4.0.0
    container_name: chrome
    ports:
      - "4444:4444"

  # ---------------------------------
  # PYTHON SERVICE
  # ---------------------------------

  python:
    build:
      context: .
      dockerfile: python/Dockerfile
    container_name: python
    depends_on:
      - dwh_db
      - chrome
    working_dir: /WeatherApiDE
    volumes:
      - ./src:/WeatherApiDE/src
      - ./data:/WeatherApiDE/data
      - ./dbt:/WeatherApiDE/dbt
    ports:
      - "5678:5678"
    environment:
      DBT_PROFILES_DIR: /WeatherApiDE/dbt/profiles
    env_file:
      - .env

  # # ---------------------------------
  # # METABASE SERVICE
  # # ---------------------------------

  # metabase:
  #   image: metabase/metabase:v0.50.10
  #   container_name: metabase
  #   ports:
  #     - "${METABASE_PORT}:3000"
  #   environment:
  #     MB_DB_TYPE: h2
  #     MB_DB_FILE: /metabase-data/metabase.db
  #   depends_on:
  #     - weather_db
  #   volumes:
  #     - metabase_data:/metabase-data
  #   healthcheck:
  #     test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
  #     interval: 30s
  #     timeout: 30s
  #     retries: 20
  #     start_period: 30s

  # # ---------------------------------
  # # METABASE INITIALIZATION
  # # ---------------------------------

  # metabase-init:
  #   build: ./metabase
  #   env_file:
  #     - .env
  #   environment:
  #     METABASE_URL: ${METABASE_URL}
  #     METABASE_USER: ${METABASE_USER}
  #     METABASE_PASSWORD: ${METABASE_PASSWORD}
  #     DB_HOST: db
  #     DB_PORT: ${DB_PORT}
  #     DB_NAME: ${DB_NAME}
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #   depends_on:
  #     metabase:
  #       condition: service_healthy
  #   restart: "no"

  # -------------------------
  # AIRFLOW DATABASE
  # -------------------------

  airflow_db:
    image: postgres:15
    container_name: airflow_db
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB_HOST}
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data

  # -------------------------
  # AIRFLOW SERVICE
  # -------------------------

  airflow:
    image: apache/airflow:2.10.1
    container_name: airflow
    depends_on:
      - airflow_db
      - python
    env_file:
      - .env
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}"
      AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_STARTTLS: True
      AIRFLOW__SMTP__SMTP_SSL: False
      AIRFLOW__SMTP__SMTP_USER: ${AIRFLOW__SMTP__SMTP_USER}
      AIRFLOW__SMTP__SMTP_PASSWORD: ${AIRFLOW__SMTP__SMTP_PASSWORD}
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ${AIRFLOW__SMTP__SMTP_MAIL_FROM}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
    command: >
      bash -c "
        echo 'Waiting for Postgres...';
        while ! nc -z "${AIRFLOW_DB_HOST}" "${AIRFLOW_DB_PORT}"; do
          sleep 2;
        done;

        echo 'Initializing Airflow DB (only first run)...';
        airflow db migrate;

        echo 'Creating admin user (idempotent)...';
        airflow users create --username "${AIRFLOW_ADMIN_USERNAME}" --password "${AIRFLOW_ADMIN_PASSWORD}" --firstname "${AIRFLOW_ADMIN_FIRSTNAME}" --lastname "${AIRFLOW_ADMIN_LASTNAME}" --role Admin --email "${AIRFLOW_ADMIN_EMAIL}" || true;

        echo 'Waiting for init.py...';
        while true; do
          if [[ "$(head -n 1 /opt/airflow/src/logs/init_done)" == "DONE" ]]; then
            break;
          elif [[ "$(head -n 1 /opt/airflow/src/logs/init_done)" == "ERROR" ]]; then
            echo 'Error in init.py. Check /src/logs/init.log';
            exit 1;
          fi;
          sleep 10;
        done;

        echo 'Starting scheduler & webserver';
        airflow scheduler & 
        exec airflow webserver
      "
    ports:
      - "8080:8080"

volumes:
  pgdata:
  metabase_data:
  airflow_pgdata: