version: "3.9"

services:

  # ---------------------------------
  # DATABASE
  # ---------------------------------

  dwh_db:
    image: postgres:15
    container_name: dwh_db
    environment:
      POSTGRES_USER: ${DWH_DB_USER}
      POSTGRES_PASSWORD: ${DWH_DB_PASSWORD}
      POSTGRES_DB: ${DWH_DB_NAME}
    ports:
      - "5432:${DWH_DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - de_net

  # ---------------------------------
  # CHROME SERVICE
  # ---------------------------------

  chrome:
    image: selenium/standalone-chrome:4.0.0
    container_name: chrome
    ports:
      - "4444:4444"
    networks:
      - de_net

  # # ---------------------------------
  # # SPARK MASTER
  # # ---------------------------------

  spark-master:
    build:
      context: .
      dockerfile: spark/Dockerfile
    container_name: spark-master
    hostname: spark-master
    environment:
      SPARK_MODE: master
      JAVA_HOME: /opt/java/openjdk
      JDK_JAVA_OPTIONS: --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
    command: >
      bash -c "/opt/spark/sbin/start-master.sh
      --host spark-master
      --port 7077
      --webui-port 8081 && tail -f /dev/null"
    ports:
      - "8081:8081"
    volumes:
      - ./src:/WeatherApiDE/src
    env_file:
      - .env
    depends_on:
      - dwh_db
    networks:
      - de_net

  # # ---------------------------------
  # # SPARK WORKER
  # # ---------------------------------

  spark-worker:
    build:
      context: .
      dockerfile: spark/Dockerfile
    container_name: spark-worker
    hostname: spark-worker
    environment:
      SPARK_MODE: worker
      JAVA_HOME: /opt/java/openjdk
      JDK_JAVA_OPTIONS: --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
    command: >
      bash -c "/opt/spark/sbin/start-worker.sh
      spark://spark-master:7077 && tail -f /dev/null"
    volumes:
      - ./src:/WeatherApiDE/src
    env_file:
      - .env
    depends_on:
      - spark-master
    networks:
      - de_net

  # ---------------------------------
  # PYTHON SERVICE
  # ---------------------------------

  python:
    build:
      context: .
      dockerfile: python/Dockerfile
    container_name: python
    depends_on:
      - dwh_db
      - chrome
      - spark-worker
    working_dir: /WeatherApiDE
    volumes:
      - ./src:/WeatherApiDE/src
      - ./data:/WeatherApiDE/data
      - ./dbt:/WeatherApiDE/dbt
    ports:
      - "5678:5678"
    environment:
      DBT_PROFILES_DIR: /WeatherApiDE/dbt/profiles
      JAVA_HOME: /usr/lib/jvm/java-21-openjdk-amd64
      JDK_JAVA_OPTIONS: --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
      PYSPARK_PYTHON: python3
    env_file:
      - .env
    networks:
      - de_net

  # -------------------------
  # AIRFLOW DATABASE
  # -------------------------

  airflow_db:
    image: postgres:15
    container_name: airflow_db
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data
    networks:
      - de_net

  # -------------------------
  # AIRFLOW SERVICE
  # -------------------------

  airflow:
    image: apache/airflow:2.10.1
    container_name: airflow
    depends_on:
      - airflow_db
      - python
    env_file:
      - .env
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}"
      AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_STARTTLS: True
      AIRFLOW__SMTP__SMTP_SSL: False
      AIRFLOW__SMTP__SMTP_USER: ${AIRFLOW__SMTP__SMTP_USER}
      AIRFLOW__SMTP__SMTP_PASSWORD: ${AIRFLOW__SMTP__SMTP_PASSWORD}
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ${AIRFLOW__SMTP__SMTP_MAIL_FROM}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./dbt:/opt/airflow/dbt
    command: >
      bash -c "
        echo 'Waiting for Postgres...';
        while ! nc -z "${AIRFLOW_DB_HOST}" "${AIRFLOW_DB_PORT}"; do
          sleep 2;
        done;

        echo 'Initializing Airflow DB (only first run)...';
        airflow db migrate;

        echo 'Creating admin user (idempotent)...';
        airflow users create --username "${AIRFLOW_ADMIN_USERNAME}" --password "${AIRFLOW_ADMIN_PASSWORD}" --firstname "${AIRFLOW_ADMIN_FIRSTNAME}" --lastname "${AIRFLOW_ADMIN_LASTNAME}" --role Admin --email "${AIRFLOW_ADMIN_EMAIL}" || true;

        echo 'Waiting for init.py...';
        while true; do
          if [[ "$(head -n 1 /opt/airflow/src/logs/init_done)" == "DONE" ]]; then
            break;
          elif [[ "$(head -n 1 /opt/airflow/src/logs/init_done)" == "ERROR" ]]; then
            echo 'Error in init.py. Check /src/logs/init.log';
            exit 1;
          fi;
          sleep 10;
        done;

        echo 'Starting scheduler & webserver';
        airflow scheduler & 
        exec airflow webserver
      "
    ports:
      - "8080:8080"
    networks:
      - de_net

volumes:
  pgdata:
  metabase_data:
  airflow_pgdata:

networks:
  de_net:
    driver: bridge